name: ${project.name}
main: io.github.tompreuss.keepbabymobs.KeepBabyMobs
version: ${project.version}
author: tompreuss
authors: [tompreuss, bermudalocket]
website: http://github.com/tompreuss/KeepBabyMobs
api-version: 1.13
